### ISSUE TITLE
GCC 9 doesn't use aggregate construction if copy-constructor is defined

### ISSUE THREAD

**Issue by felipealmeida** [VestniK/portable_concurrency#14]
diff --git a/portable_concurrency/bits/then.hpp b/portable_concurrency/bits/then.hpp
index ae11e8f..a650267 100644
--- a/portable_concurrency/bits/then.hpp
+++ b/portable_concurrency/bits/then.hpp
@@ -151,7 +151,7 @@ struct cnt_action {
 
   cnt_action(const cnt_action&) = delete;
 
-#if defined(__GNUC__) && __GNUC__ < 5 && !defined(__clang__)
+#if defined(__GNUC__) && (__GNUC__ < 5 || __GNUC__ >= 9) && !defined(__clang__)
   cnt_action(std::weak_ptr<CntState> wdata) : wdata(std::move(wdata)) {}
   cnt_action(cnt_action&& rhs) noexcept : wdata(std::exchange(rhs.wdata, {})) {}
   cnt_action& operator=(cnt_action&& rhs) noexcept {

**Comment by VestniK** [comment]
Hello. Thank you for report. I've pushed two commits to the master branch with fix of this issue https://github.com/VestniK/portable_concurrency/commit/0df6629645307d6b08e0c31e3341bb4d4eceec20 and https://github.com/VestniK/portable_concurrency/commit/4579523388fd508b5c11e4288fb7b0868d55554b and with gcc 9 build on the travis CI.
I'll make bugfix release 0.10.1 later on during this week and close this issue.

**Comment by VestniK** [comment]
https://github.com/VestniK/portable_concurrency/releases/tag/v0.10.1 release with fix
