### ISSUE TITLE
std::result_of_t are deprecated in C++17

### ISSUE THREAD

**Issue by Logris** [VestniK/portable_concurrency#18]
Hi
Planning to do support for C ++ 17?

**Comment by VestniK** [comment]
Hi
I'll add some workaround to us `std::invoke_result` when it's available (using `__cpp_lib_is_invocable` feature test macro) during this week.

> Planning to do support for C ++ 17?
It is supported. I can successfully compile it in C++17 and C++20 mode with gcc 10 and all tests are fine. I don't think that it's time to dropp C++14 support. Some people still might be unable to switch to recent enough toolchains.
