### ISSUE TITLE
Отмена задач

### ISSUE THREAD

**Issue by Logris** [VestniK/portable_concurrency#21]
Добрый день

```
struct Tile
{
      std::unique_ptr<pc::future<ImportResult>> future_geometry_ptr;
      std::vector<pc::future<bool>> future_textures;
      std::atomic<int>  import_state;

      ~Tile()
     {
          if(import_state == ImportGeometry) {
                if(future_geometry_ptr) {
                     future_geometry_ptr->wait();
                }
          }
          future_geometry_ptr.reset();

          future_textures.clear();
     }
}
```

В деструкторе мне нужно отменить все задачи и обязательно дождаться завершения уже запущенных задач.
Сейчас у меня есть состояние, по которому я могу определить, что задача ImportGeometry выполняется и в деструкторе подождать ее. С задачами импорта текстур посложнее, например, можно завести вектор состояний (atomic_bool) для каждой задачи и отслеживать его.  

Есть другой способ реализовать такой функционал?

**Comment by woodroof** [comment]
Можно в каждую задачу, которая должна завершиться или отмениться, захватить внешний guard. И тогда ожидать уже разрушения этого guard'а. Т.е. это не через future, но вполне реализуемо.

**Comment by Logris** [comment]
Я сейчас в задачу передаю внешний atomic_bool  и в задаче выставляю его в true по завершении.

Как правильно в таком случае отменить задачи в деструкторе, чтобы пока ждешь завершения одних задач, другие не запустились?

Например, фьючерсы хранить в векторе unique_ptr  ( std::vector<std::unique_ptr<pc::future<bool>>  tasks), тогда:

```
~desructor()
{
   int index=0;
     std::vector<int> executed_indexes;

    for(auto& task :  tasks) {
       if(  !executed[index]) ) {
           task.reset();
       } else {
         executed_indexes.push_back(index);
       }
       ++index;
    }

    for(auto i  : executed_indexes) {
          tasks[i]->wait();
    }

    tasks.clear()
}
```

**Comment by Logris** [comment]
В каком месте?

**Comment by woodroof** [comment]
Там, где проверка executed. После этой проверки задача может запуститься, и мы её не будем ждать, а должны. atomic_bool не решает эту задачу в принципе.
Какое-то ревью уже получается :)

**Comment by Logris** [comment]
Т.е. нужно отменить все задачи, а потом ждать разрушения объекта, который передали в функцию исполнения?

**Comment by woodroof** [comment]
Да

**Comment by Logris** [comment]
Спасибо

**Comment by Logris** [comment]
Вот написал ExecutionGuard.  Вроде бы работает.

```
        class ExecuteGuard
	{
	public:
		ExecuteGuard() = default;
		~ExecuteGuard()
		{
			Wait();
		}

		void Wait()
		{
			std::unique_lock<std::mutex> lock{ m_state.mtx };
			m_state.cv.wait(lock, [this] { return !m_state.has_execution; });
		}
	public:
		struct Execution
		{
			Execution(ExecuteGuard& guard) : guard(guard)
			{
				guard.ExecutionAdd();
			}

			~Execution()
			{
				guard.ExecutionRelease();
			}

			ExecuteGuard& guard;
		};

	private:
		void ExecutionAdd()
		{
			std::unique_lock<std::mutex> lock{ m_state.mtx };

			m_execution_count++;
			m_state.has_execution = true;
		}

		void ExecutionRelease() {
			std::unique_lock<std::mutex> lock{ m_state.mtx };

			m_execution_count--;
			if (m_execution_count == 0)
			{
				m_state.has_execution = false;
				m_state.cv.notify_one();
			}
		}

	private:
		struct State
		{
			std::mutex mtx;
			std::condition_variable cv;
			bool has_execution{ false };
		};

	private:
		std::atomic_int m_execution_count{ 0 };
		State m_state;
	};
```

Использование:
  
```
ExecuteGuard guard;

auto future = pc::async(executor, [guard = &guard] () {
   ExecuteGuard::Execution _{guard};
   ...... 
});

guard.Wait();
```

**Comment by woodroof** [comment]
has_execution лишний, и атомик не нужен, раз есть мьютекс. Но примерно так, да.
Но вообще плохая идея спамить на Сергея и подписчиков. И тикет предлагаю закрыть, раз есть решение.
